---
- name: Crear reporte máquina virtual en Hyper-V
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtener información sobre todas las máquinas virtuales
      win_shell: |
          $VMs = Get-VM
          $VMReport = $VMs | Select-Object Name, State, MemoryAssigned, ProcessorCount, Uptime, @{Name="CPU Usage (%)";Expression={(Get-VMProcessor -VMName $_.Name).ProcessorLoad}}, @{Name="Disk Size (GB)";Expression={((Get-VMHardDiskDrive -VMName $_.Name).Size / 1GB).ToString("0.##")}}
          $VMReport | ConvertTo-Csv -NoTypeInformation
      register: vm_report

    - name: Crear archivo CSV en el servidor de Windows
      win_copy: 
        content: "{{ vm_report.stdout }}"
        dest: "C:\\Users\\jarivera\\Documents\\Inventarios\\VMReport.csv"

    - name: Envio email
      community.general.mail:
        host: smtp.office365.com
        port: 587
        username: notificacion@asesuisa.com
        password: '{{passnotify_host}}'
        from: notificacion@asesuisa.com
        to: 
            - jarivera@asesuisa.com
        subject: "Reporte vm"
        body: "Reporte de vm's Hyper V en clusters asesuisa"
        # attach: /home/giotomato/playbooks/VMReport.csv
        secure: starttls
      delegate_to: localhost
