---
- name: Instalacion de servidor web nginx a los servidores
  hosts: linux
  gather_facts: no
  tasks:
    - name: Instalando nginx
      include_role: name=nginx_rol
      tags: install
    
    - name: Desintalando nginx
      include_role: name=nginx_rol_uninstall
      tags: uninstall
