- name: Desinstalar Nginx
  apt:
    name: nginx
    state: absent

- name: Eliminar directorio de la p치gina de prueba
  file:
    path: /var/www/html/prueba
    state: absent
    recurse: yes

- name: Eliminar configuraci칩n de Nginx
  file:
    path: /etc/nginx/sites-available/prueba
    state: absent

- name: Eliminar enlace simb칩lico de configuraci칩n de Nginx
  file:
    path: /etc/nginx/sites-enabled/prueba
    state: absent